@startuml system_structure

  component placeholder
  google -- auth0  
  auth0 -- ddd_master_editor
  auth0 -- xxx_xxx_xxx
  auth0 -- client_app_001
  ddd_master_editor -- ddd_master_editor_bff
  xxx_xxx_xxx -- xxx_xxx_xxx_bff
  ddd_master_editor_bff -- gateway
  xxx_xxx_xxx_bff -- gateway
  user_backend_app -- gateway
  gateway -- cloudflare_r2_adapter
  gateway -- cloudflare_d1_adapter
  gateway -- google_drive_adapter
  gateway -- github_adapter

  hide @unlinked
@enduml